server:
  port: 8110
###为服务起名称，该服务注册到Eureka注册中心的名称，比如商品服务
spring:
  application:
    name: app-item

eureka:
  client:
    service-url:
      defaultZone: http://zkx:123456@127.0.0.1:8112/eureka/,http://zkx:123456@127.0.0.1:9112/eureka/,http://zkx:123456@127.0.0.1:9113/eureka/
    #该应用为服务提供者，是Eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    #是否需要从Eureka上检索服务
    fetch-registry: true
  instance:
    #将自己的ip地址注册到Eureka服务中
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #指定实例id
    instance-id: ${spring.application.name}###${server.port}
