server:
  port: 8110
###为服务起名称，该服务注册到Eureka注册中心的名称，比如商品服务
spring:
  application:
    name: app-item

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    virtual-host: testhost1

    #消息确认配置项
    #确认消息已经发送到交换机（exchange）
    publisher-confirms: true
    #确认消息已经发送到队列（queue）
    publisher-returns: true

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 1000
    # 连接池
    jedis:
      pool:
        # 连接池中最大空闲连接
        max-idle: 10
        # 连接池中最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8

mybatis:
  config-location: classpath:mybatisconfig.xml
  mapper-locations: classpath:mapper/**/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://zkx:123456@127.0.0.1:8112/eureka/,http://zkx:123456@127.0.0.1:9112/eureka/,http://zkx:123456@127.0.0.1:9113/eureka/
    #该应用为服务提供者，是Eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    #是否需要从Eureka上检索服务
    fetch-registry: true
  instance:
    #将自己的ip地址注册到 Eureka 服务中
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #指定实例id
    instance-id: ${spring.application.name}###${server.port}



